all: linux solaris10

linux: 
	javac -Xlint -classpath /Tdata/public/SDC/current/libs/jchart2d-2.1.1.jar:./src -sourcepath ./src -d ./bin ./src/*.java

solaris10: 
	javac -Xlint -classpath /Tdata/public/SDC/current/libs/jchart2d-2.1.1.jar:./src -sourcepath ./src -d ./bin_solaris10 ./src/*.java
